Feature/subjects
ZulyVargas/Academic-Registry pull request #4
Opened 2023-03-02 16:19 UTC by ZulyVargas

2023-03-06 04:20 UTC, nordonezc requested changes

2023-03-06 04:20 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/controller/SubjectController.java
> +    @GetMapping(value="/paged/{limit}/{offset}")
limit y offset no deberian ser manejados mejor con @RequestParam. Porque manejarlo como un @PathVariable?

2023-03-06 04:20 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/dto/SubjectDTO.java
> +@SuperBuilder
Porque @SuperBuilder? podrias usar un @Builder?

Se podria reemplazar @Getter, @Setter y @AllArgsconstructor por @Data?

2023-03-06 04:20 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/dto/SubjectDTO.java
> +    private String subjectId;
Si recibes un UUID directamente te podrias evitar la validación de Regexp?

2023-03-06 04:20 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/entities/Subject.java
> +    @Transient
Porque usar @transient? En que casos se utiliza?

2023-03-06 04:20 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/exception/Error.java
> +@AllArgsConstructor
Se puede usar @Data?

2023-03-06 04:20 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/exception/RequestExceptionHandler.java
> +        return  new ResponseEntity<>(response,HttpStatus.BAD_REQUEST);
Como manejas excepciones diferentes a MethodArgumentNotValidException?

2023-03-06 04:20 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/exception/ResponseExceptionHandler.java
> +        return  new ResponseEntity<>(error,HttpStatus.NOT_FOUND);
Que error manejas si la base de datos está caída?

2023-03-06 04:20 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/mappers/ISubjectMapper.java
> +@Mapper
Que propiedades recibe mapper? Pregunta para control en llamada

2023-03-06 04:20 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/repository/ISubjectRepository.java
> +    @Query("SELECT * FROM SUBJECTS ORDER BY credits LIMIT :limit OFFSET :offset ")
Debería estar condicionada la query a que busque solo los subjects que no se han eliminado?

2023-03-06 04:20 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/services/impl/SubjectService.java
> +    public SubjectService(ISubjectRepository subjectRepository, ISubjectMapper subjectMapper) {
Es necesario que yo ponga el @Autowired? Si estoy definiendo mis dependencias como final y adicional en el constructor? es redundante?

2023-03-06 04:20 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/services/impl/SubjectService.java
> +    private Set<Subject> findPrerrequisitesById(UUID subjectId) {
métodos privados deberian ir al final de la clase? o en que parte deberían ir? cual es el criterio que utilizaste para dejarlo aqui?

2023-03-06 14:54 UTC, ACarrasquilla07 commented on src/main/java/com/perficient/courseregistry/app/exception/RequestExceptionHandler.java
> +        exception.getBindingResult().getAllErrors().forEach((e) -> {
Aquí puedes usar un map

2023-03-06 14:54 UTC, ACarrasquilla07 commented on src/main/java/com/perficient/courseregistry/app/exception/RequestExceptionHandler.java
> +            Error error = new Error(((FieldError)e).getField(), e.getDefaultMessage(), HttpStatus.BAD_REQUEST, ZonedDateTime.now(ZoneId.of("America/Bogota")));
Esto lo puedes poner en un método y usar una lamda

2023-03-06 14:54 UTC, ACarrasquilla07 commented on src/main/java/com/perficient/courseregistry/app/services/impl/SubjectService.java
> +        Set<SubjectDTO> subjects = subjectList.stream()
Aquí puedes retornar de una vez, no hay necesidad de crear la variable "subjects"

2023-03-06 14:54 UTC, ACarrasquilla07 commented on src/main/java/com/perficient/courseregistry/app/services/impl/SubjectService.java
> +        Set<Subject> prerrequisites = this.subjectRepository.findPrerrequisitesById(subjectId)
Aquí puedes retornar de una vez, no hay necesidad de crear la variable "prerrequisites"

2023-03-07 19:56 UTC, nordonezc requested changes
Revisar los ultimos cambios sobreo todo en la definición de las URIs, los comentarios que ya se resolvieron, por fa, marcarlos como resuelto

2023-03-07 19:56 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/controller/SubjectController.java
> +    @GetMapping(value="/paged")
esta bien nombrado esta operación?

2023-03-07 19:56 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/dto/SubjectDTO.java
> +    private String credits;
Numero de creditos no deberia ser un Integer?

2023-03-07 19:56 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/entities/Subject.java
> +    private String credits;
Creditos deberia ser un Integer?

2023-03-07 19:56 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/repository/ISubjectRepository.java
> +public interface ISubjectRepository extends CrudRepository<Subject,String> {
Agregar a la consulta que esten filtrados por lo que aún existen por defecto, pero que permita tambien filtrar por todos

2023-03-07 19:56 UTC, nordonezc commented on src/main/java/com/perficient/courseregistry/app/services/ISubjectService.java
> +    Set<SubjectDTO> getAllSubjectsPaged(Integer limit, Integer offset);
Si es necesario diferenciar el getAll del getallPaged?

2023-03-09 17:38 UTC, nordonezc approved these changes
Well done

2023-03-10 19:49 UTC, ACarrasquilla07 approved these changes
Veo el código bien

2023-03-10 19:58 UTC, merged